name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating Systems to build (comma separated, e.g. macos-latest,ubuntu-latest,windows-latest)'
        required: false
        default: 'ubuntu-latest,macos-latest,windows-latest'

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          # Read the input and remove any whitespace
          INPUT_OS="${{ github.event.inputs.os }}"
          echo "Received OS input: '$INPUT_OS'"
          # Convert the comma-separated list into a JSON array.
          MATRIX=$(echo "[\"$(echo ${INPUT_OS} | sed 's/,/","/g')\"]")
          echo "Generated matrix: $MATRIX"
          # New recommended way to set output:
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build:
    needs: generate-matrix
    strategy:
      matrix:
        os: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Verify tag matches version
        if: startsWith(github.ref, 'refs/tags/')
        id: verify_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_VERSION=${GITHUB_REF#refs/tags/v}
            PACKAGE_VERSION=$(node -p "require('./package.json').version")
            if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
              echo "Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
              exit 1
            fi
          fi
        shell: bash

      - name: Inject secrets
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env

      - name: Build app
        run: npm run build

      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install snapcraft --classic

      - name: Package app
        run: npm run electron:build:${{ matrix.arch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true  # or false, depending on your needs
          files: |
            dist_electron/*.dmg
            dist_electron/*.deb
            dist_electron/*.exe
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
