name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger only on version tags like v1.0.0

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        arch: [x64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install snapcraft --classic
        
      - name: Package app
        run: npm run electron:build -- --${{ matrix.arch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist_electron/*.dmg
            dist_electron/*.deb
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
